# Generated by Django 3.0.6 on 2022-10-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='area',
        ),
    ]
