# Generated by Django 3.0.6 on 2022-11-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=5, unique=True)),
                ('hos_id', models.CharField(max_length=5)),
                ('user_id', models.CharField(max_length=5)),
                ('star', models.CharField(blank=True, max_length=2000, null=True)),
                ('picture', models.CharField(blank=True, max_length=2000, null=True)),
                ('detail', models.CharField(blank=True, max_length=2000, null=True)),
                ('heart', models.CharField(blank=True, max_length=2000, null=True)),
                ('price', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
