# Generated by Django 3.0.6 on 2022-11-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hos_id', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
                ('address', models.CharField(blank=True, max_length=2000, null=True)),
                ('subway', models.CharField(blank=True, max_length=1000, null=True)),
                ('facilitly', models.CharField(blank=True, max_length=3000, null=True)),
                ('animal', models.CharField(blank=True, max_length=2000, null=True)),
                ('clinic', models.CharField(blank=True, max_length=2000, null=True)),
                ('open_time', models.TextField(blank=True, null=True)),
                ('break_time', models.CharField(blank=True, max_length=2000, null=True)),
                ('picture', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
